import assert from 'node:assert/strict';
import { toCents, fromCents } from '../src/utilities.js';
import { migrateV10ToV11, migrateToV12, migrateToV13, normalizeLedgerTransaction } from '../src/migrations.js';
import { accountBalanceFromLedger } from '../src/calculations.js';
import { addRecurringFrequency, recurringOccurrenceId } from '../src/recurring.js';
import { safeToSpendBreakdown, chooseBestAction } from '../src/planning.js';
import { canEnableCloudSync, pinMeetsPolicy, syncRequirements } from '../src/security.js';
assert.equal(toCents('12.34'), 1234);
assert.equal(toCents('$1,234.56'), 123456);
assert.equal(fromCents(987), 9.87);
const v10 = { schemaVersion: 10, accounts: [{ id: 'checking', name: 'Checking', balance: 100 }], incomeSources: [{ id: 'pay', name: 'Paycheck', amount: 500, accountId: 'checking', date: '2026-07-01' }], expenses: [{ id: 'food', name: 'Food', amount: 25.25, accountId: 'checking', date: '2026-07-02' }], transactions: [] };
const migrated = migrateV10ToV11(v10);
assert.equal(migrated.schemaVersion, 11);
assert.equal(migrated.accounts[0].openingBalanceCents, 10000);
assert.equal(migrated.ledger.length, 2);
assert.equal(migrated.ledger.find((item) => item.id === 'food').amountCents, 2525);
const transfer = normalizeLedgerTransaction({ type: 'transfer', amount: 30, accountId: 'checking', destinationAccountId: 'savings' });
assert.equal(transfer.amountCents, 3000);
assert.equal(accountBalanceFromLedger({ id: 'checking', openingBalanceCents: 10000 }, [transfer]), 7000);
assert.equal(accountBalanceFromLedger({ id: 'savings', openingBalanceCents: 0 }, [transfer]), 3000);
assert.equal(addRecurringFrequency('2026-07-01', 'weekly'), '2026-07-08');
assert.equal(addRecurringFrequency('2026-07-01', 'biweekly'), '2026-07-15');
assert.equal(addRecurringFrequency('2026-07-01', 'quarterly'), '2026-10-01');
assert.equal(recurringOccurrenceId('rent', '2026-08-01'), 'rent:2026-08-01');
const v12 = migrateToV12(v10);
assert.equal(v12.schemaVersion, 12);
assert.deepEqual(v12.paycheckPlans, []);
assert.deepEqual(v12.monthlyReviews, []);
assert.equal(v12.settings.safeToSpendPeriod, 'week');
const safe = safeToSpendBreakdown({ cash: 1000, buffer: 200, obligations: [{ amount: 150 }, { amount: 50 }], start: '2026-07-01', end: '2026-07-04' });
assert.equal(safe.safeAmount, 600);
assert.equal(safe.dailyAmount, 150);
assert.equal(chooseBestAction({ dueSoon: [{ title: 'Rent' }], safeAmount: 100 }), 'handle-due-item');
assert.equal(chooseBestAction({ dataIssueCount: 2, safeAmount: 100 }), 'clean-data');
assert.equal(chooseBestAction({ safeAmount: 0 }), 'hold-spending');
const v13 = migrateToV13(v10);
assert.equal(v13.schemaVersion, 13);
assert.equal(v13.settings.lockEnabled, false);
assert.equal(v13.settings.syncProvider, 'none');
assert.equal(pinMeetsPolicy('1234'), true);
assert.equal(pinMeetsPolicy('12'), false);
assert.equal(canEnableCloudSync({ hasAuth: true, hasDatabase: true, hasConflictResolution: true, hasAuditRestore: true }), true);
assert.equal(canEnableCloudSync({ hasAuth: true, hasDatabase: true }), false);
assert.equal(syncRequirements().filter((item) => item.required).length >= 4, true);
console.log('Ledgerly v2 tests passed');
